--- # My First YAML playbook
- hosts: demo
  user: ansible
  become: yes
  connection: ssh
  tasks:
    - name: Install HTTPD server on centos 7
      action: yum name=httpd state=installed
      notify: restart HTTPD   #is called only if the action is ran & successful #
  handlers:
    - name: restart HTTPD   #has to match the notify name. Otherwise throws error #
      action: service name=httpd state=restarted

